name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 2 * * * #8 AM IST
    - cron: 00 14 * * * #730 PM IST
jobs: 
  run-postman-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install NodeJS and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Install newman and Html-extra globally
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
      - name: Run the Postman collection with Newman
        run: |
              newman run 'InWarranty-Flow Copy.postman_collection.json' \
              -e 'QA Copy.postman_environment.json' \
              -r cli,htmlextra
      - name: Newman Report
        uses: actions/upload-artifact@v6.0.0
        with: 
         name: Newman Report
         path: newman/*.html
          
